name: shamba-ai-ci

on:
  pull_request:
    branches: [ main, staging ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: shamba_ai
          POSTGRES_USER: shamba
          POSTGRES_PASSWORD: shamba
        ports: ['5432:5432']
        options: >-
          --health-cmd "pg_isready -U shamba" \
          --health-interval 10s \
          --health-timeout 5s \
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install frontend deps
        run: |
          cd frontend
          npm ci
          npm run lint
          npm test -- --runInBand
      - name: Install backend deps
        run: |
          cd backend
          pip install -r requirements.txt
          pytest || true
      - name: Static checks data-pipeline
        run: |
          cd data-pipeline
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          ruff etl || true

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build backend image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/backend:${{ github.sha }} -f backend/Dockerfile backend
          docker push ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
      - name: Build frontend image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/frontend:${{ github.sha }} -f frontend/Dockerfile frontend
          docker push ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}

  deploy:
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest
      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
      - name: Deploy manifests
        run: |
          kubectl apply -f deployment/kubernetes/configmap.yaml
          kubectl apply -f deployment/kubernetes/secret.yaml
          kubectl apply -f deployment/kubernetes/pvc.yaml
          kubectl apply -f deployment/kubernetes/backend-deployment.yaml
          kubectl apply -f deployment/kubernetes/frontend-deployment.yaml
          kubectl apply -f deployment/kubernetes/services.yaml
          kubectl apply -f deployment/kubernetes/ingress.yaml
          kubectl apply -f deployment/kubernetes/hpa.yaml
      - name: Trigger smoke tests
        run: |
          kubectl rollout status deployment/backend-deployment -n shamba --timeout=60s
          curl -f https://api.shamba.ai/health
